### ISSUE TITLE
Remote Reward Server & Reinforced Fine-tuning

### ISSUE THREAD

**Issue by sherlockl01** [OpenRLHF/OpenRLHF#1118]
Is there a problem with the document?
from: https://openrlhf.readthedocs.io/en/latest/remote_rm.html
```
@app.post("/get_reward")
async def get_reward(request: Request):
    data = await request.json()
    queries = data.get("query")
    rewards = reward_model.get_reward(queries)
    result = {"rewards": rewards, "scores": rewards, "extra_logs": {"dummy_scores": rewards}}
    logger.info(f"Sent JSON: {result}")
    return JSONResponse(result)
```
from the api, the result should be a dictionary with lists like:
```
{
    "rewards":[0.5, 0.1], 
    "scores": [0.5, 0.1], 
    "extra_logs": 
        {
            "dummy_scores": [0.5, 0.1]
        }
}
```
but in the code:
OpenRLHF/openrlhf/trainer/ppo_utils/experience_maker.py 
function:update_samples_with_rewards line 205, 
```
ef update_samples_with_rewards(rewards_info, samples_list):
    """Process rewards info and update samples with rewards, scores and extra logs.

    Args:
        rewards_info: List of reward information dictionaries (from HTTP JSON)
        samples_list: List of Experience objects to update
    """
    # Process rewards and scores
    samples_len = [len(sample.sequences) for sample in samples_list]
    rewards_list = torch.cat([info["rewards"] for info in rewards_info], dim=0).split(samples_len)
```
seem that the rewards_info should be a list of dictionaries like:
```
[
    {"rewards":xxx, "scores":xxx}, 
    {"rewards":xxx, "scores":xxx}, 
    ...
]
```

where the Traceback is:
  File "/openrlhf/trainer/ppo_trainer.py", line 450, in fit
    rollout_samples = self.samples_generator.generate_samples(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/openrlhf/trainer/ppo_utils/experience_maker.py", line 266, in generate_samples
    rollout_samples = self._generate_vllm(all_prompts, all_labels, **generate_kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openrlhf/trainer/ppo_utils/experience_maker.py", line 408, in _generate_vllm
    # Get rewards info from remote model
    rewards_info = ray.get(remote_reward_model.get_rewards.remote(all_queries, all_prompts, all_labels))
    # Process rewards and scores    
    update_samples_with_rewards(rewards_info, samples_list)
  File "/openrlhf/trainer/ppo_utils/experience_maker.py", line 215, in update_samples_with_rewards
    rewards_list = torch.cat([info["rewards"] for info in rewards_info], dim=0).split(samples_len)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected Tensor as element 0 in argument 0, but got list

**Comment by hijkzzz** [comment]
Yes this is a bug, welcome to fix it

**Comment by sherlockl01** [comment]
fix by updating the function at OpenRLHF/openrlhf/trainer/ppo_utils/experience_maker.py

```
def update_samples_with_rewards(rewards_info, samples_list):
    """Process rewards info and update samples with rewards, scores and extra logs.

    Args:
        rewards_info: List of reward information dictionaries
        samples_list: List of Experience objects to update
    """
    # Process rewards and scores
    samples_len = [len(sample.sequences) for sample in samples_list]

    rewards_list = torch.cat([torch.as_tensor(info["rewards"]) for info in rewards_info], dim=0).split(samples_len)
    if "scores" in rewards_info[0]:
        scores_list = torch.cat([torch.as_tensor(info["scores"]) for info in rewards_info], dim=0).split(samples_len)
    else:
        scores_list = rewards_list

    # Process extra_logs if present
    if "extra_logs" in rewards_info[0]:
        # Merge all extra_logs tensors first
        merged_logs = {
            key: torch.cat([torch.as_tensor(logs[key]) for logs in [info["extra_logs"] for info in rewards_info]], dim=0).split(
                samples_len
            )
            for key in rewards_info[0]["extra_logs"].keys()
        }

    # Update samples with rewards, scores and extra logs
    for i, samples in enumerate(samples_list):
        samples.rewards = rewards_list[i]
        samples.scores = scores_list[i]
        samples.info["score"] = scores_list[i]
        samples.info["reward"] = rewards_list[i]
        if "extra_logs" in rewards_info[0]:
            for key, values in merged_logs.items():
                samples.info[key] = values[i]

    return samples_list
```

**Comment by hijkzzz** [comment]
> fix by updating the function at OpenRLHF/openrlhf/trainer/ppo_utils/experience_maker.py
> 
> ```
> def update_samples_with_rewards(rewards_info, samples_list):
>     """Process rewards info and update samples with rewards, scores and extra logs.
> 
>     Args:
>         rewards_info: List of reward information dictionaries
>         samples_list: List of Experience objects to update
>     """
>     # Process rewards and scores
>     samples_len = [len(sample.sequences) for sample in samples_list]
> 
>     rewards_list = torch.cat([torch.as_tensor(info["rewards"]) for info in rewards_info], dim=0).split(samples_len)
>     if "scores" in rewards_info[0]:
>         scores_list = torch.cat([torch.as_tensor(info["scores"]) for info in rewards_info], dim=0).split(samples_len)
>     else:
>         scores_list = rewards_list
> 
>     # Process extra_logs if present
>     if "extra_logs" in rewards_info[0]:
>         # Merge all extra_logs tensors first
>         merged_logs = {
>             key: torch.cat([torch.as_tensor(logs[key]) for logs in [info["extra_logs"] for info in rewards_info]], dim=0).split(
>                 samples_len
>             )
>             for key in rewards_info[0]["extra_logs"].keys()
>         }
> 
>     # Update samples with rewards, scores and extra logs
>     for i, samples in enumerate(samples_list):
>         samples.rewards = rewards_list[i]
>         samples.scores = scores_list[i]
>         samples.info["score"] = scores_list[i]
>         samples.info["reward"] = rewards_list[i]
>         if "extra_logs" in rewards_info[0]:
>             for key, values in merged_logs.items():
>                 samples.info[key] = values[i]
> 
>     return samples_list
> ```

maybe we can update the openrlhf-doc?

**Comment by sherlockl01** [comment]
I don't think it's necessary. I found that the shape of rewards_info is [num_node], like [{"rewards":[0.1, 0.5]}, {"rewards":[0.4, 0.3]}, ...]. Thus, the logic of the code is right. The error is just a detail, which is the native python list passed through the server api. This list cannot be directly used with torch.cat. 
```
torch.cat([info["rewards"] for info in rewards_info], dim=0).split(samples_len) ❌
```
For this reason, I updated the code (see above) and first converted this list into a tensor object. please update the code if it's convenient for you. Thanks!

**Comment by ShikangWang** [comment]
This commit doesn't completely resolve the issue - if "extra_logs" exists, line 228 will still raise the same error.

> I don't think it's necessary. I found that the shape of rewards_info is [num_node], like [{"rewards":[0.1, 0.5]}, {"rewards":[0.4, 0.3]}, ...]. Thus, the logic of the code is right. The error is just a detail, which is the native python list passed through the server api. This list cannot be directly used with torch.cat.
> 
> ```
> torch.cat([info["rewards"] for info in rewards_info], dim=0).split(samples_len) ❌
> ```
> 
> For this reason, I updated the code (see above) and first converted this list into a tensor object. please update the code if it's convenient for you. Thanks!
